export const reduxActionTypes = {
    /**
     * USER ACTION TYPE
    */
    SET_USER: "SET_USER",
    REMOVE_USER: "REMOVE_USER",

    /**
     * POSTS ACTION TYPE
    */
    SET_POSTS: "SET_POSTS",
    DELETE_POSTS: "DELETE_POSTS",
    UPDATE_POSTS: "UPDATE_POSTS",
    GET_MORE_POSTS: "GET_MORE_POSTS",
    SET_POSTS_HASE_MORE: "SET_POSTS_HASE_MORE",
    SET_POSTS_STARTAT: "SET_POSTS_STARTAT",
    SET_POSTS_ENDAT: "SET_POSTS_ENDAT",
    CRATE_POST: "CRATE_POST",

    /**
     * TODOS ACTION TYPE
    */
    SET_TODOS: "SET_TODOS",
    GET_MORE_TODOS: "GET_MORE_TODOS",
    SET_TODOS_HASMORE: "SET_TODOS_HASMORE",
    SET_TODOS_STARTAT: "SET_TODOS_STARTAT",
    SET_TODOS_ENDAT: "SET_TODOS_ENDAT",
    CRATE_TODOS: "CRATE_TODOS",
}