export const reduxActionTypes = {
    SET_USER: "SET_USER",
    REMOVE_USER: "REMOVE_USER",
    SET_POSTS: "SET_POSTS",
    GET_MORE_POSTS: "GET_MORE_POSTS",
    SET_POSTS_TOTOAL_ITEMS_COUNT: "SET_POSTS_TOTOAL_ITEMS_COUNT",
    CRATE_POST: "CRATE_POST",
    UPDATE_POST: "UPDATE_POST",
    DELETE_POST: "DELETE_POST",
}